server:
  port: 80

spring:
  datasource:
    #连接数据库
    url: jdbc:mysql://122.51.56.154:3306/springBoot2.0?useSSL=false
    username: fanghuiping
    password: KKry100@qq.com
    driver-class-name: com.mysql.cj.jdbc.Driver

